### ISSUE TITLE
请使用TOTP工具扫描下方二维码

### ISSUE THREAD

**Issue by xzeu** [sec-report/SecAutoBan#1]
请问TOTP工具在哪里下载，没看到相关说明信息

**Comment by SecAegis** [comment]
手机应用市场任意TOTP验证器即可，例如微软的：[authenticator](https://support.microsoft.com/zh-cn/account-billing/%E4%B8%8B%E8%BD%BD%E5%B9%B6%E5%AE%89%E8%A3%85microsoft-authenticator%E5%BA%94%E7%94%A8-351498fc-850a-45da-b7b6-27e523b8702a)
